// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkjGE7G10Sf4sQhQRByGhJOSLeSiIvxsI',
    appId: '1:414619040223:web:e033e3fe8d8a80e93cac6a',
    messagingSenderId: '414619040223',
    projectId: 'corporate-chat-app',
    authDomain: 'corporate-chat-app.firebaseapp.com',
    storageBucket: 'corporate-chat-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6RMS7JBVT2l0-hWV9oxZT3WQVK0uuTcs',
    appId: '1:414619040223:android:80fd81b27487e5193cac6a',
    messagingSenderId: '414619040223',
    projectId: 'corporate-chat-app',
    storageBucket: 'corporate-chat-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvHejpzPCYEPCZ13vAypp_oCni0YcI_4g',
    appId: '1:414619040223:ios:efdc5692c8809e983cac6a',
    messagingSenderId: '414619040223',
    projectId: 'corporate-chat-app',
    storageBucket: 'corporate-chat-app.appspot.com',
    iosClientId: '414619040223-j0n0tpjdi0ceuqijf7nvtactn1qdn8v6.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvHejpzPCYEPCZ13vAypp_oCni0YcI_4g',
    appId: '1:414619040223:ios:efdc5692c8809e983cac6a',
    messagingSenderId: '414619040223',
    projectId: 'corporate-chat-app',
    storageBucket: 'corporate-chat-app.appspot.com',
    iosClientId: '414619040223-j0n0tpjdi0ceuqijf7nvtactn1qdn8v6.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
